services:
  pg1:
    image: reg.local.seatone.com/common/postgres/postgres-timedb:15-alpine3.19
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=rXh@7!J46hD57Yh
    volumes:
      - ./pg_data:/var/lib/postgresql/data
