// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDesktopSettings() {
  return window['go']['main']['App']['GetDesktopSettings']();
}

export function LaunchRDP(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['LaunchRDP'](arg1, arg2, arg3, arg4);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function SaveDesktopSettings(arg1) {
  return window['go']['main']['App']['SaveDesktopSettings'](arg1);
}
