// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetDesktopSettings():Promise<main.DesktopSettings>;

export function LaunchRDP(arg1:string,arg2:number,arg3:string,arg4:string):Promise<void>;

export function Quit():Promise<void>;

export function SaveDesktopSettings(arg1:main.DesktopSettings):Promise<main.DesktopSettings>;
